name: esm-catalog-builder
channels:
  - conda-forge
  - nodefaults
dependencies:
  - dask
  - ncar-jobqueue
  - netcdf4
  - pandas
  - pip
  - pip
  - python
  - rich
  - typer
  - xarray
  - pip:
      - git+https://github.com/xarray-contrib/cf-xarray.git
      - git+https://github.com/NCAR/ecgtools.git
